server:
  port: 8888

#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        ddl-auto: create
#    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:h2:file:/Users/linverno/test;DB_CLOSE_ON_EXIT=TRUE
#    url: jdbc:h2:~/test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: root1234

